name:        "MSBuild"
description: "MSBuild"

inputs:
 file:
  required: true
 configuration:
  required: true
 arguments:
  required: false

branding:
 icon:  'tool'
 color: 'white'

runs:
 using: 'composite'
 steps:

 - run:   "$(vswhere -latest -requires Microsoft.Component.MSBuild -find MSBuild/**/Bin/MSBuild.exe)" "${{ inputs.file }}" -p:Configuration=${{ inputs.configuration }} ${{ inputs.arguments }}
   shell: bash
