name:        "MSBuild"
description: "MSBuild"

inputs:
 vswhere:
  required: false
  default:  "-latest -requires Microsoft.Component.MSBuild -find MSBuild/**/Bin/MSBuild.exe"
 file:
  required: true
 configuration:
  required: true
 arguments:
  required: false

branding:
 icon:  'tool'
 color: 'white'

runs:
 using: 'composite'
 steps:

 - run:   |
          "$(vswhere ${{ inputs.vswhere }})" "${{ inputs.file }} -p:Configuration=${{ inputs.configuration }} ${{ inputs.arguments }}
   shell: bash
