name:        "MSBuild"
description: "MSBuild"

inputs:
 file:
  required: true
 configuration:
  required: true
 arguments:
  required: false

branding:
 icon:  'tool'
 color: 'white'

runs:
 using: 'composite'
 steps:

 - run:   |
          :
          GHA_MSBUILD_EXE="$("/c/Program Files (x86)/Microsoft Visual Studio/Installer/vswhere.exe" -latest -requires Microsoft.Component.MSBuild -find MSBuild/**/Bin/MSBuild.exe)"
          "$GHA_MSBUILD_EXE" "${{ inputs.file }}" -p:Configuration=${{ inputs.configuration }} ${{ inputs.arguments }}
   shell: bash
